import "./globals.css";
import { Inter } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  currentUser,
} from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header className="flex justify-between container mx-auto items-center py-3">
            <Link href="/">
              <h1>Todo App</h1>
            </Link>
            <SignedIn>
              <div className="flex gap-4 items-center">
                <span className="text-blue-400">{user && user.firstName}</span>
                <UserButton afterSignOutUrl="/" />
              </div>
            </SignedIn>
            <SignedOut>
              <SignInButton mode="modal" />
            </SignedOut>
          </header>
          <main className="container mx-auto mt-4">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
